2025-05-15 00:07:08,329 ERROR: Exception on /user/Person2 [GET] [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: followers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\templates\user.html", line 13, in block 'content'
    <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\models.py", line 75, in followers_count
    return db.session.scalar(query)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\orm\scoping.py", line 1841, in scalar
    return self._proxied.scalar(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\orm\session.py", line 2413, in scalar
    return self._execute_internal(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: followers
[SQL: SELECT count(*) AS count_1 
FROM (SELECT user.id AS id, user.username AS username, user.email AS email, user.password_hash AS password_hash, user.about_me AS about_me, user.last_seen AS last_seen 
FROM user, followers 
WHERE followers.followed_id = ? AND followers.follower_id = user.id) AS anon_1]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-15 00:07:30,298 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 00:07:48,377 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 00:07:54,869 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 00:07:58,925 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 00:08:11,015 ERROR: Exception on /user/Susan [GET] [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\BlogVenv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\routes.py", line 72, in user
    abort(404)
NameError: name 'abort' is not defined
2025-05-15 00:10:19,211 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 00:10:25,656 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 02:01:25,909 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 03:30:51,661 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:39]
2025-05-15 04:45:58,021 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:40]
2025-05-15 04:50:40,623 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:40]
2025-05-15 05:06:07,534 INFO: Microblog startup [in C:\Users\Blaika\Desktop\2025SummerProjects\ProjectBasedLearning\FlaskMicroBlog\app\__init__.py:40]
